### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by arctic-alpaca**
Should fix ci and enable conditional release upload action to prevent ci fails when all but `Upload Release (Android)` succeed.

### CODE REVIEW

**Comment by arctic-alpaca** [comment]
I'm not sure why this is failing. It worked in the forked repo: https://github.com/arctic-alpaca/flutterust/actions/runs/533668937

**Comment by arctic-alpaca** [comment]
I only found this part that references length in `ChanTsune/release-with-commit@v2.0.1`:

https://github.com/ChanTsune/release-with-commit/blob/36ca756ec024d175ed56ebfecaedd1eedcd0d08d/src/index.ts#L17-L22

I think this might be a problem on github's side, I already encountered other issues with actions today.

**Comment by arctic-alpaca** [comment]
I suspect this is a cache problem. I changed the cache keys to check. If this succeeds, I'll remove the commit again as to not mess up your cache keys.

**Comment by arctic-alpaca** [comment]
I have no idea why this isn't working. Any input would be appreciated.

**Comment by shekohex** [comment]
You know what? Let's merge this, and I can find this issue later!

Thank you @arctic-alpaca for the PR!

**Pull request merged**
