### PR TITLE
ported to flutter 2.12.0 and ffi 1.0.0

### PR DESCRIPTION
**Pull request by JoschuaL**
Bumped minimum flutter version to 2.12 and ffi version to 1.0.0
This included making adder and scrap null-safe, tough sound null safety is still stuck on the isolate package not being null save.

### CODE REVIEW

**Comment by JoschuaL** [comment]
just noticed, the CI runs with sound null savety, which fails because of the isolate package. So I suppose the CI script would need to be changed for now to run with `--no-sound-null-safety
`

**Comment by shekohex** [comment]
Yeah, it's not a big deal as these just an example to demonstrate how the package could be used, so it's fine to add this flag to the CI!

**Comment by JoschuaL** [comment]
ok, I have no idea why the CI tasks fail. the android one seems to error when running chantsune (I don't even know what that is) and the ios one just gets aborted out of nowhere.

**Comment by shekohex** [comment]
I guess that means we need to update/upgrade the actions version. could you try to see if there is an upgrade for that action version?

**Comment by arctic-alpaca** [comment]
I also had some problems with it when trying [to fix the CI](https://github.com/shekohex/flutterust/pull/20) and I'm still unsure what's happening there.

I hope it's alright to suggest this, but is the release part of the CI actually needed? I'm not sure this repo needs releases since it is mostly an example on how to use Flutter with Rust.

**Comment by shekohex** [comment]
Yeah, I agree fair enough .. I will make another PR to remove the Release part, nonetheless this PR I guess is ready to be merged.

**Comment by shekohex** [comment]
Thanks @JoschuaL 

Merged :tada:

**Pull request merged**
